name: voila-gallery-country-indicators
channels:
- conda-forge
dependencies:
- voila
- fastai>=2
- pillow<7
- packaging
- ipywidgets==7.5.1
- numpy==1.19.5
- pandas==1.1.3
- scipy==1.5.2
- seaborn==0.11.0
- matplotlib==3.3.2
- ipywidgets==7.6.3
- jupyterlab>=3.1
